const MovieSchedule = require("../model/movie");
const isEmpty = require("../helper/is-empty");
const loadSeed = async () => {
  try {
    const schedule = await MovieSchedule.find({});
    //check if seed is already loaded

    if (isEmpty(schedule)) {
      //insert seed data if data is empty
      const scheduleContent = [
        {
          date: "2021-01-19",
          times: [
            {
              time: "10:30AM",
              reserved: [
                "B3",
                "B2",
                "C3",
                "D3",
                "E2",
                "D2",
                "G3",
                "G1",
                "H7",
                "I7",
                "A5",
                "B6",
                "C5",
                "C6",
                "D6",
                "E1",
                "D1",
                "C1",
                "E3",
                "F3",
                "H2",
                "J2",
                "J3",
                "K3",
                "K2",
                "J5",
                "J6",
                "I6",
                "I5",
                "H5",
                "H6",
                "F7",
              ],
              availability: "available",
            },
            {
              time: "1:00PM",
              reserved: [
                "A2",
                "A3",
                "C3",
                "C1",
                "D2",
                "E2",
                "E1",
                "F3",
                "A5",
                "B6",
                "B7",
                "C5",
                "F7",
                "F6",
                "G6",
                "G7",
                "I7",
                "I6",
                "I5",
              ],
              availability: "available",
            },
            {
              time: "6:00AM",
              reserved: [
                "B3",
                "B2",
                "C3",
                "D3",
                "E2",
                "D2",
                "G3",
                "G1",
                "H7",
                "I7",
                "A5",
                "B6",
                "C5",
                "C6",
                "D6",
              ],
              availability: "available",
            },
          ],
        },
        {
          date: "2021-01-20",

          times: [
            {
              time: "10:30AM",
              reserved: ["I3", "I2", "I1", "H1", "F2", "E2", "H3"],
              availability: "available",
            },
            {
              time: "1:00PM",
              reserved: ["G7", "H7", "I7", "J7", "E6", "E5", "F3"],
              availability: "available",
            },
            {
              time: "3:30PM",
              reserved: [
                "G7",
                "H7",
                "I7",
                "J7",
                "E6",
                "E5",
                "F3",
                "K3",
                "H1",
                "H2",
                "F2",
                "E2",
                "D2",
                "C2",
                "B2",
                "A2",
                "A3",
                "B3",
                "C3",
                "D3",
                "E3",
                "D1",
                "E1",
                "C1",
                "B1",
                "G1",
                "F1",
                "G2",
                "G3",
                "H3",
                "I3",
                "I2",
                "I1",
                "J1",
                "J2",
                "J3",
                "K2",
                "K5",
                "K6",
                "J5",
                "J6",
                "I6",
                "I5",
                "H5",
                "H6",
                "G6",
                "G5",
                "F5",
                "F7",
                "F6",
                "E7",
                "D7",
                "D6",
                "C6",
                "C7",
                "D5",
                "C5",
                "B5",
                "B6",
                "B7",
                "A6",
                "A5",
              ],
              availability: "not-available",
            },
            {
              time: "6:00AM",
              reserved: ["F7", "F6", "E7", "D7", "D6"],
              availability: "available",
            },
          ],
        },
        {
          date: "2021-01-21",

          times: [
            {
              time: "10:30AM",
              reserved: ["I7", "C2", "K1"],
              availability: "available",
            },
            {
              time: "1:00PM",
              reserved: ["A1", "I5", "D3", "F3", "B4"],
              availability: "available",
            },

            {
              time: "6:00AM",
              reserved: ["C2", "C3", "K4"],
              availability: "available",
            },
          ],
        },
        {
          date: "2021-01-23",

          times: [
            {
              time: "10:30AM",
              reserved: [
                "G7",
                "H7",
                "I7",
                "J7",
                "E6",
                "E5",
                "F3",
                "K3",
                "H1",
                "H2",
                "F2",
                "E2",
                "D2",
                "C2",
                "B2",
                "A2",
                "A3",
                "B3",
                "C3",
                "D3",
                "E3",
                "D1",
                "E1",
                "C1",
                "B1",
                "G1",
                "F1",
                "G2",
                "G3",
                "H3",
                "I3",
                "I2",
                "I1",
                "J1",
                "J2",
                "J3",
                "K2",
                "K5",
                "J5",
                "J6",
                "I6",
                "I5",
                "H5",
                "H6",
                "G6",
                "G5",
                "F5",
                "F7",
                "E7",
                "D7",
                "D6",
                "C6",
                "C7",
                "D5",
                "C5",
                "B5",
                "B7",
                "A6",
                "A5",
              ],
              availability: "available",
            },
            {
              time: "3:30PM",
              reserved: ["B3", "B2", "C3", "D3", "E2", "D2", "G3"],
              availability: "available",
            },

            {
              time: "6:00AM",
              reserved: [
                "F7",
                "F6",
                "E7",
                "D7",
                "D6",
                "C6",
                "C7",
                "D5",
                "C5",
                "B5",
              ],
              availability: "available",
            },
            {
              time: "9:00AM",
              reserved: ["B1"],
              availability: "available",
            },
          ],
        },
        {
          date: "2021-01-24",

          times: [
            {
              time: "10:30AM",
              reserved: ["B7", "D1", "F1"],
              availability: "available",
            },
            {
              time: "1:00PM",
              reserved: ["b1", "I5", "E3", "F3", "E7"],
              availability: "available",
            },
            {
              time: "3:30PM",
              reserved: ["A3", "B4", "C3", "D3", "E7", "F1", "G6"],
              availability: "available",
            },
            {
              time: "6:00AM",
              reserved: [""],
              availability: "available",
            },
            {
              time: "9:00AM",
              reserved: ["A2", "E3", "E4"],
              availability: "available",
            },
          ],
        },
        {
          date: "2021-01-25",

          times: [
            {
              time: "3:30PM",
              reserved: ["A3", "B4", "C3", "D3", "E7", "F1", "G6"],
              availability: "available",
            },

            {
              time: "6:00AM",
              reserved: [""],
              availability: "available",
            },
          ],
        },
      ];

      await MovieSchedule.insertMany(scheduleContent);
      return true;
    } else {
      return true;
    }
  } catch (error) {
    console.error(error.message);
    //Exit process with failure
    return false;
  }
};

module.exports = loadSeed;
